import Head from "next/head";


type Props = {
  title?: string
  description?: string
  favicon?: string
}

export default function HeadMeta({
                                   title = 'Next App',
                                   description = "Generated by create next app",
                                   favicon = "/favicon.ico"
                                 }: Props) {

  return (
      <Head>
        <title>{title}</title>
        <meta name="description" content={description}/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href={favicon}/>
      </Head>

  );
}
